baseURL = "https://novaclearnscyber.github.io/blog/"
languageCode = 'ro-ro'
title = 'Cyber Blog-ul lui Novac'

# SETĂRI CORECTE PENTRU GITHUB PAGES
canonifyURLs = true
relativeURLs = false

# Display virtually all posts on one page
[pagination]
  pagerSize = 9999

# Allow raw HTML in markdown posts
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

  # Mount standard content directory (REQUIRED when defining custom mounts)
  [[module.mounts]]
    source = 'content'
    target = 'content'

  # Adăugăm mounts-urile esențiale pentru a nu pierde CSS-ul temei
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'

[params]
  # Custom Banner Image
  # Place the image in 'static/images/' and reference it here
  # banner = "images/my-banner.jpg"
  banner = "static/siteBackcopy.png"
  banner_height = "450px"
