baseURL = "https://novadearnscyber.github.io/blog/"
languageCode = 'ro-ro'
title = 'Cyber Blog-ul lui Novac'
theme = "github.com/hugo-sid/hugo-blog-awesome"

# Rezolvă problemele de căi pe GitHub Pages
canonifyURLs = false
relativeURLs = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

  # Mapăm folderul tău de postări (care se numește 'blog') direct la 'content'
  [[module.mounts]]
    source = 'blog'
    target = 'content'

  # Mount-uri necesare pentru ca tema să funcționeze corect
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'static'
    target = 'static'
