baseURL = "https://novaclearnscyber.github.io/blog/"
languageCode = 'ro-ro'
title = 'Cyber Blog-ul lui Novac'
theme = "github.com/hugo-sid/hugo-blog-awesome"

# Setări vitale pentru căi corecte pe GitHub Pages
canonifyURLs = false
relativeURLs = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

  # Mapăm folderul tău 'blog' către conținut
  [[module.mounts]]
    source = 'blog'
    target = 'content/posts'

  # IMPORTANT: Trebuie să adăugăm manual restul folderelor standard, 
  # altfel Hugo le ignoră pe cele din temă!
  [[module.mounts]]
    source = 'static'
    target = 'static'

  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'

  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'