baseURL = "https://novaclearnscyber.github.io/blog/"
languageCode = 'ro-ro'
title = 'Cyber Blog-ul lui Novac'
theme = "github.com/hugo-sid/hugo-blog-awesome"

canonifyURLs = true
relativeURLs = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

  [[module.mounts]]
    source = 'blog'
    target = 'content/posts'

  # Adăugăm și folderul static în mounts pentru siguranță
  [[module.mounts]]
    source = 'static'
    target = 'static'