baseURL = "https://novadearnscyber.github.io/blog/"
languageCode = 'ro-ro'
title = 'Cyber Blog-ul lui Novac'
theme = "github.com/hugo-sid/hugo-blog-awesome"

# Rezolvă problemele de CSS pe subfoldere
canonifyURLs = false
relativeURLs = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

  # Spunem lui Hugo că postările tale sunt în folderul numit 'blog' din rădăcină
  [[module.mounts]]
    source = 'blog'
    target = 'content'

  # Trebuie să punem și restul de mounts, altfel tema se strică
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'static'
    target = 'static'
