baseURL = 'https://novaclearnscyber.github.io/blog/'
canonifyURLs = true
languageCode = 'ro-ro'
title = 'Cyber Blog-ul lui Novac'
theme = "github.com/hugo-sid/hugo-blog-awesome"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
    baseURL = 'https://novaclearnscyber.github.io/blog/'

  [[module.mounts]]
    source = 'blog' 
    target = 'content/posts'
    baseURL = 'https://novaclearnscyber.github.io/blog/'